# Generated by Django 5.1.3 on 2026-01-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='operation',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('VALIDATE_GROUP_CREATION', 'Validate Group Creation'), ('VALIDATE_OPERATION', 'Validate Operation'), ('NONE', 'None')], default='NONE', max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='available_actions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_reference',
            field=models.CharField(db_index=True, default='LEGACY', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='source_type',
            field=models.CharField(choices=[('TEMP_GROUP_CREATION', 'Temp Group Creation'), ('OPERATION', 'Operation'), ('GROUP', 'Group')], default='LEGACY', max_length=30),
            preserve_default=False,
        ),
    ]
