# Generated by Django 5.1.3 on 2025-12-17 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('initiator_phone_number', models.CharField(db_index=True, max_length=20)),
                ('validator_max_number', models.PositiveIntegerField(default=5)),
                ('quorum', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('INITIATOR', 'Initiator'), ('VALIDATOR', 'Validator')], max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.validationgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'phone_number'), name='unique_member_per_group'), models.UniqueConstraint(fields=('group', 'cin'), name='unique_cin_per_group')],
            },
        ),
    ]
