# Generated by Django 5.1.3 on 2025-12-23 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryGroupCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_phone_number', models.CharField(db_index=True, max_length=20)),
                ('group_name', models.CharField(max_length=100)),
                ('quorum', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryGroupValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('has_accepted', models.BooleanField(null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('temp_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='groups.temporarygroupcreation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('temp_group', 'phone_number'), name='unique_temp_validator_phone'), models.UniqueConstraint(fields=('temp_group', 'cin'), name='unique_temp_validator_cin')],
            },
        ),
    ]
