# Generated by Django 5.1.3 on 2025-12-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_temporarygroupcreation_temporarygroupvalidator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('initiator_phone_number', models.CharField(db_index=True, max_length=20)),
                ('operation_type', models.CharField(choices=[('ADD_VALIDATOR', 'Add validator'), ('REMOVE_VALIDATOR', 'Remove validator'), ('DELETE_GROUP', 'Delete group')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='groups.validationgroup')),
            ],
        ),
        migrations.CreateModel(
            name='OperationValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('validator_phone_number', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='groups.operation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('operation', 'validator_phone_number'), name='unique_validator_per_operation')],
            },
        ),
    ]
