# Generated by Django 5.1.3 on 2025-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_operation_operationvalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationvalidation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
    ]
