# Generated by Django 5.1.3 on 2025-12-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_operationvalidation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationvalidation',
            name='validator_phone_number',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
