# Generated by Django 5.1.3 on 2025-12-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_operationvalidation_validator_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationvalidation',
            name='validation_reference',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
