# Generated by Django 5.1.3 on 2025-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_operationvalidation_validation_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationvalidation',
            name='validation_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
