# Generated by Django 4.2 on 2026-02-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_operationvalidation_validation_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAddValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_phone_number', models.CharField(db_index=True, max_length=20)),
                ('validator_phone_number', models.CharField(db_index=True, max_length=20)),
                ('validator_cin', models.CharField(max_length=50)),
                ('has_accepted', models.BooleanField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_validator_additions', to='groups.validationgroup')),
            ],
            options={
                'db_table': 'groups_temp_add_validator',
            },
        ),
        migrations.AddIndex(
            model_name='temporaryaddvalidator',
            index=models.Index(fields=['validator_phone_number'], name='groups_temp_validat_a659b7_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryaddvalidator',
            index=models.Index(fields=['initiator_phone_number'], name='groups_temp_initiat_6bce94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temporaryaddvalidator',
            unique_together={('group', 'validator_phone_number', 'is_cancelled')},
        ),
    ]
