# Generated by Django 4.2 on 2026-02-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_temporaryaddvalidator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryaddvalidator',
            name='validator_cin',
        ),
    ]
