# Generated by Django 4.2 on 2026-02-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_temporaryaddvalidator_validator_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationvalidation',
            name='has_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
