# Generated by Django 4.2 on 2026-02-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_operationvalidation_has_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15),
        ),
    ]
