# Generated by Django 4.2 on 2026-02-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_operation_completed_at_alter_operation_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_member_per_group',
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('group', 'phone_number'), name='unique_member_per_group'),
        ),
    ]
