# Generated by Django 4.2 on 2026-02-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_remove_groupmembership_unique_member_per_group_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_cin_per_group',
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('group', 'cin'), name='unique_cin_per_group'),
        ),
    ]
