# Generated by Django 4.2 on 2026-03-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_remove_groupmembership_unique_cin_per_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('ADD_VALIDATOR', 'Add validator'), ('REMOVE_VALIDATOR', 'Remove validator'), ('DELETE_GROUP', 'Delete group'), ('TRANSACTION', 'Transaction')], max_length=30),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='groups.operation')),
            ],
        ),
    ]
