# Generated by Django 4.2 on 2026-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_transaction_reference_account_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'USER')), fields=('owner_user',), name='unique_user_account'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'GROUP')), fields=('owner_group',), name='unique_group_account'),
        ),
    ]
