# Generated by Django 4.2 on 2026-03-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_transaction_reference_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=15),
        ),
    ]
