# Generated by Django 4.2 on 2026-03-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_rename_account_accounts'),
    ]

    operations = [
    ]
