# Generated by Django 4.2 on 2026-03-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_auto_20260305_1137'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_user_account',
        ),
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_group_account',
        ),
    ]
