# Generated by Django 4.2 on 2026-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('SUPERADMIN', 'SuperAdmin')], default='USER', max_length=20),
        ),
    ]
